/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carniceriamr.Ventanas;

import carniceriamr.Conexion;

/**
 *
 * @author santi
 */
public class FrmVentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVentas.class.getName());
private void calcularTotal() {
    String textoCantidad = TextCantidadVender.getText().trim();
    if (textoCantidad.isEmpty()) {
        LabelTotal.setText("$ 0.00");
        return;
    }

    try {
        double cantidad = Double.parseDouble(textoCantidad);
        String carneSeleccionada = CarneVenderComboBox.getSelectedItem().toString();

        carniceriamr.Conexion cn = new carniceriamr.Conexion();
        java.sql.Connection con = cn.conectar();

        String sql = "SELECT precio FROM productos WHERE nombre = ?";
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, carneSeleccionada);
        java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            double precio = rs.getDouble("precio");
            double total = precio * cantidad;
            LabelTotal.setText(String.format("$ %.2f", total));
        }
    } catch (Exception e) {
        LabelTotal.setText("$ 0.00");
    }
}
    /**
     * Creates new form FrmVentas
     */
    public FrmVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CarneVenderComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextCantidadVender = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CarneVenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bistec de Res", "Arrachera Marinada", "Rib Eye", "Molida de Res", "T-Bone", "Chuleta de Cerdo", "Lomo de Cerdo", "Costilla de Cerdo", "Pulpita de Cerdo", "Pechuga Entera", "Milanesa de Pollo", "Pierna y Muslo", "Alitas de Pollo", "Longaniza Casera", "Chorizo Español" }));
        CarneVenderComboBox.addActionListener(this::CarneVenderComboBoxActionPerformed);

        jLabel1.setText("Pantalla de Ventas ");

        jLabel2.setText("Carne a vender");

        jLabel3.setText("Cantidad");

        TextCantidadVender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextCantidadVenderKeyReleased(evt);
            }
        });

        jButton1.setText("Realizar venta");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel4.setText("Total");

        LabelTotal.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(CarneVenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TextCantidadVender, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelTotal)
                        .addGap(149, 149, 149))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarneVenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCantidadVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(LabelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                
   
    // que no este vacio el txt
    if (TextCantidadVender.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Ingresa la cantidad a vender.");
        return;
    }

    
    String carneSeleccionada = CarneVenderComboBox.getSelectedItem().toString(); //agarramos la carne seleccionada en el cb
    double cantidadAVender = Double.parseDouble(TextCantidadVender.getText().trim()); //covertir el txt a double

    try {
        carniceriamr.Conexion cn = new carniceriamr.Conexion();
        java.sql.Connection con = cn.conectar();

        // 3. Buscamos id_producto, precio y stock
        String sqlBuscar = "SELECT id_producto, precio, stock FROM productos WHERE nombre = ?";
        java.sql.PreparedStatement psBuscar = con.prepareStatement(sqlBuscar);
        psBuscar.setString(1, carneSeleccionada);
        java.sql.ResultSet rs = psBuscar.executeQuery();

        if (rs.next()) {
            int idProducto = rs.getInt("id_producto");
            double precio = rs.getDouble("precio");
            double stockActual = rs.getDouble("stock");

            if (cantidadAVender > stockActual) {
                javax.swing.JOptionPane.showMessageDialog(null, "¡No hay suficiente stock! Disponible: " + stockActual + " KG");
            } else {
                double total = precio * cantidadAVender;
                double nuevoStock = stockActual - cantidadAVender;

                // A. Restamos el stock en la tabla productos
                String sqlUpdate = "UPDATE productos SET stock = ? WHERE id_producto = ?";
                java.sql.PreparedStatement psUpdate = con.prepareStatement(sqlUpdate);
                psUpdate.setDouble(1, nuevoStock);
                psUpdate.setInt(2, idProducto);
                psUpdate.executeUpdate();

                // B. REGISTRAMOS LA VENTA GENERAL
                String sqlVenta = "INSERT INTO ventas (id_cliente, total) VALUES (1, ?)";
                java.sql.PreparedStatement psVenta = con.prepareStatement(sqlVenta, java.sql.Statement.RETURN_GENERATED_KEYS);
                psVenta.setDouble(1, total);
                psVenta.executeUpdate();

                // Obtenemos el id_venta recién creado
                java.sql.ResultSet rsVenta = psVenta.getGeneratedKeys();
                int idVentaGenerado = -1;
                if (rsVenta.next()) {
                    idVentaGenerado = rsVenta.getInt(1);
                }

                // C. REGISTRAMOS EL DETALLE DE LA VENTA
                if (idVentaGenerado != -1) {
                    String sqlDetalle = "INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio, subtotal) VALUES (?, ?, ?, ?, ?)";
                    java.sql.PreparedStatement psDetalle = con.prepareStatement(sqlDetalle);
                    psDetalle.setInt(1, idVentaGenerado);
                    psDetalle.setInt(2, idProducto);
                    psDetalle.setDouble(3, cantidadAVender);
                    psDetalle.setDouble(4, precio);
                    psDetalle.setDouble(5, total);
                    psDetalle.executeUpdate();
                }

                // D. Notificación e interfaz
                LabelTotal.setText(String.format("$ %.2f", total));
                javax.swing.JOptionPane.showMessageDialog(null, "¡Venta realizada con éxito!\nTotal: $" + total);

                TextCantidadVender.setText("");
                calcularTotal();
            }
        }
        con.close();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error en la venta: " + e.getMessage());
    }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextCantidadVenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCantidadVenderKeyReleased
                                                     
    calcularTotal();

    }//GEN-LAST:event_TextCantidadVenderKeyReleased

    private void CarneVenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarneVenderComboBoxActionPerformed
                                                    
    calcularTotal();
        // TODO add your handling code here:
    }//GEN-LAST:event_CarneVenderComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CarneVenderComboBox;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTextField TextCantidadVender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
